query GetProjectMembers($project:ID!,$cursor:String){
    project(fullPath: $project){
        projectMembers(first: 20,after: $cursor){
            nodes {
                id
                user {
                    namespace {
                        name
                    }
                    name

                }

                createdAt
            }
            pageInfo {
                endCursor
                hasPreviousPage
                hasNextPage
                startCursor
            }
        }
    }
}