query GetProjectPipelines($project:ID!,$cursor:String,$status:PipelineStatusEnum){
    project(fullPath: $project){
        id
        pipelines(first: 20,status: $status ,after: $cursor ){
            __typename
            nodes {
                status
                duration
                finishedAt
                id
                name
            }
            pageInfo {
                hasNextPage
                startCursor
                endCursor
                hasPreviousPage
            }
        }
    }
}