query GetProjectRepository($projectPath:ID!,$branch:String,$path:String,$blobsCursor:String,$treeCursor:String){
    project(fullPath: $projectPath){
        id
        name
        repository {
            rootRef
            tree(ref: $branch,path:$path){
                __typename
                lastCommit(ref: $branch){
                    message
                    id
                    committedDate
                    author {
                        name
                    }
                }
                trees(first: 20,after:$treeCursor){
                    __typename

                    nodes {
                        id
                        name
                        path

                    }
                    pageInfo {
                        endCursor
                        hasNextPage
                    }
                }
                blobs(first: 20,after:$blobsCursor){
                    nodes {
                        id
                        name
                        path
                    }
                    pageInfo {
                        endCursor
                        hasNextPage
                    }
                }
            }
        }
    }
}